-- 0003_app_schema.sql
-- Phase 1: the `app` schema (NextAuth adapter tables + query_log) and the `app_rw` role.
--
-- Two-role model (project_plan.md §5, .agents/p1_query_api.md §2): `app_rw` owns the
-- application's own reads/writes (auth, logging, rate-limit lookups); user SQL runs only as
-- `sandbox_ro`. A compromise of the app connection therefore cannot mutate `nba` data or
-- widen grants -- app_rw has DML on `app` tables only, no DDL (it owns nothing) and no
-- access to `nba` at all.
--
-- `sandbox_ro` gets NO grants here. db/tests/test_sandbox_ro.py, which previously asserted
-- isolation against a simulated `app` schema, asserts it against this real one from now on.
--
-- Like sandbox_ro, app_rw ships with a NULL password and cannot authenticate until one is
-- provisioned out of band: ALTER ROLE app_rw PASSWORD '<from the secret store>';

BEGIN;

-- ---------------------------------------------------------------------------
-- The role. Same shape and reasoning as sandbox_ro's (0002): LOGIN with its own
-- connection string, NOINHERIT, capped connections.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_rw') THEN
        CREATE ROLE app_rw
            LOGIN
            NOSUPERUSER
            NOCREATEDB
            NOCREATEROLE
            NOINHERIT
            NOREPLICATION
            NOBYPASSRLS
            CONNECTION LIMIT 10;
    END IF;
END
$$;

ALTER ROLE app_rw
    LOGIN
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    CONNECTION LIMIT 10;

COMMENT ON ROLE app_rw IS
  'Application role: DML on schema app (NextAuth tables, query_log) only. No access to nba; no DDL. User SQL never runs as this role -- that is sandbox_ro. See db/tests/test_app_rw.py.';

CREATE SCHEMA IF NOT EXISTS app;

-- ---------------------------------------------------------------------------
-- NextAuth adapter tables, exactly as @auth/pg-adapter expects them (its queries
-- hardcode these table/column names, unqualified -- the app reaches them by setting
-- search_path=app on the app_rw pool). Two deliberate deviations from the adapter's
-- reference schema.sql: identity columns instead of SERIAL (no sequence grants to
-- manage) and text instead of varchar(255) (no reason to cap).
-- ---------------------------------------------------------------------------
CREATE TABLE app.users (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text,
    email           text,
    "emailVerified" timestamptz,
    image           text
);

CREATE TABLE app.accounts (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId"            integer NOT NULL REFERENCES app.users(id) ON DELETE CASCADE,
    type                text NOT NULL,
    provider            text NOT NULL,
    "providerAccountId" text NOT NULL,
    refresh_token       text,
    access_token        text,
    expires_at          bigint,
    id_token            text,
    scope               text,
    session_state       text,
    token_type          text,
    UNIQUE (provider, "providerAccountId")
);

CREATE TABLE app.sessions (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId"       integer NOT NULL REFERENCES app.users(id) ON DELETE CASCADE,
    expires        timestamptz NOT NULL,
    "sessionToken" text NOT NULL UNIQUE
);

CREATE TABLE app.verification_token (
    identifier text NOT NULL,
    token      text NOT NULL,
    expires    timestamptz NOT NULL,
    PRIMARY KEY (identifier, token)
);

-- ---------------------------------------------------------------------------
-- Audit log. One row per execution attempt -- success, validation rejection, timeout,
-- error alike (AGENTS.md critical rule). Columns that only exist for executed queries
-- (duration_ms, row_count) are nullable so a validation_rejected row can be written.
--
-- user_id is nullable with ON DELETE SET NULL, not CASCADE: the log is the abuse audit
-- trail and the rate-limit source, and deleting an account must not erase its history.
-- The route always writes a user id -- NULL only ever arises from a later user deletion.
--
-- Append-only for the app: app_rw gets INSERT + SELECT (rate-limit sliding window reads
-- recent rows per user/IP), never UPDATE or DELETE.
-- ---------------------------------------------------------------------------
CREATE TABLE app.query_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer REFERENCES app.users(id) ON DELETE SET NULL,
    client_ip   inet,
    query_text  text NOT NULL,
    status      text NOT NULL
                CHECK (status IN ('ok', 'validation_rejected', 'timeout', 'error')),
    started_at  timestamptz NOT NULL DEFAULT now(),
    duration_ms integer,
    row_count   integer,
    truncated   boolean NOT NULL DEFAULT false,
    error_text  text
);

-- Both rate-limit windows scan "recent rows for this user/IP" -- index exactly that.
CREATE INDEX query_log_user_started_idx   ON app.query_log (user_id, started_at DESC);
CREATE INDEX query_log_client_started_idx ON app.query_log (client_ip, started_at DESC);

-- ---------------------------------------------------------------------------
-- Grants: table-scoped, never schema-wide, same policy as 0002 -- a future table in
-- `app` is not exposed to app_rw until granted here explicitly.
-- ---------------------------------------------------------------------------
GRANT USAGE ON SCHEMA app TO app_rw;

GRANT SELECT, INSERT, UPDATE, DELETE ON app.users              TO app_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON app.accounts           TO app_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON app.sessions           TO app_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON app.verification_token TO app_rw;

GRANT SELECT, INSERT ON app.query_log TO app_rw;

ALTER ROLE app_rw SET search_path = app;

COMMIT;
