-- 0004_agent_conversations.sql
-- Phase 4: agent conversations, plus provenance and linkage on query_log.
--
-- Two things happen here and they belong in one migration because the second depends on the
-- first: the agent tab needs somewhere to persist a thread, and every row the agent puts in
-- app.query_log needs to be attributable back to the message that caused it.
--
-- `source` is the provenance column. It exists because agent and eval traffic share the
-- execution chain (and therefore the audit trail) with human editor traffic, and "who issued
-- this query" stops being answerable the moment three clients write indistinguishable rows.
-- It is set by the API route that authenticated the caller, NEVER read off the request body --
-- a caller that can name its own provenance can launder it. The DEFAULT exists only so that
-- the Phase 1-3 INSERT (which predates this column) keeps working; new code passes it.
--
-- Both new tables are app-owned state, so app_rw gets full DML on them. `sandbox_ro` gets
-- NOTHING here, same as 0003: user SQL must not be able to see other users' conversations,
-- and the only thing standing between it and them is the absence of a grant. query_log stays
-- append-only for app_rw -- no UPDATE, no DELETE -- which this migration does not relax.

BEGIN;

-- ---------------------------------------------------------------------------
-- A conversation is a thread in the agent tab. Deleting a user deletes their
-- conversations outright (CASCADE), unlike query_log, whose user_id is nullable with
-- ON DELETE SET NULL: query_log is the abuse audit trail and must outlive the account,
-- while a conversation is the user's own content and has no reason to.
--
-- title is nullable because a thread exists from its first message, before anything has
-- named it. updated_at is denormalized rather than derived from max(message.created_at)
-- so the left rail can order threads without touching the message table.
-- ---------------------------------------------------------------------------
CREATE TABLE app.conversation (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer NOT NULL REFERENCES app.users(id) ON DELETE CASCADE,
    title      text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- The left rail's only query: this user's threads, most recently active first.
CREATE INDEX conversation_user_updated_idx ON app.conversation (user_id, updated_at DESC);

-- ---------------------------------------------------------------------------
-- One turn in a thread. `content` is JSONB rather than columns because the assistant's
-- payload is the agent envelope (outcome / summary / sql / a result reference) and its shape
-- will keep moving through Phase 4; a user turn is just text. Pinning that to columns now
-- would mean a migration per envelope field.
--
-- STORAGE CONSTRAINT -- this is the design's load-bearing decision, not a note:
-- `content` MUST NOT hold a full QueryResult. The row cap is 1000 rows per query, and a
-- 40-turn thread of thousand-row JSONB results would dwarf the 216MB of actual NBA data on
-- the Supabase free tier (.agents/p4_agent.md, resolved 2026-08-06 #6). An assistant turn
-- stores the SQL, a reference to the app.query_log row that executed it (via
-- query_log.conversation_message_id, below), and at most a truncated preview (<= 50 rows).
-- Full results are re-executed on demand, never persisted here.
-- ---------------------------------------------------------------------------
CREATE TABLE app.conversation_message (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint NOT NULL REFERENCES app.conversation(id) ON DELETE CASCADE,
    role            text NOT NULL CHECK (role IN ('user', 'assistant')),
    content         jsonb NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN app.conversation_message.content IS
  'Agent envelope (assistant) or question text (user). NEVER a full QueryResult -- store sql + the query_log reference + a <=50-row preview and re-execute on demand; 1000-row results here would outgrow the dataset itself. See db/migrations/0004.';

-- Rendering a thread reads every message for one conversation in order, and `id` is
-- monotonic within a conversation, so this one index serves the read AND backs the
-- ON DELETE CASCADE from app.conversation (an unindexed FK makes deleting a thread a
-- sequential scan of every message ever written).
CREATE INDEX conversation_message_conversation_idx
    ON app.conversation_message (conversation_id, id);

-- ---------------------------------------------------------------------------
-- query_log gains provenance and a link back to the turn that caused it.
--
-- The link is nullable and lives on query_log rather than on the message because most
-- query_log rows have no message at all (editor traffic), and because one turn can produce
-- several attempts -- the agent's correction ladder retries, and every attempt is logged.
-- ON DELETE SET NULL, not CASCADE: deleting a conversation must not erase audit rows.
-- ---------------------------------------------------------------------------
ALTER TABLE app.query_log
    ADD COLUMN source text NOT NULL DEFAULT 'editor'
        CHECK (source IN ('editor', 'agent', 'eval'));

COMMENT ON COLUMN app.query_log.source IS
  'Which entry point executed this query: editor (/api/query, session-gated) | agent | eval (/api/internal/query, service-token-gated). Set by the endpoint from the credential that authenticated it, never from the request body.';

ALTER TABLE app.query_log
    ADD COLUMN conversation_message_id bigint
        REFERENCES app.conversation_message(id) ON DELETE SET NULL;

-- Partial: only agent traffic sets this column, so the index covers the rows that are
-- actually looked up ("what did this turn execute?") and skips every editor row. It also
-- keeps the ON DELETE SET NULL above from scanning all of query_log per deleted message.
CREATE INDEX query_log_conversation_message_idx
    ON app.query_log (conversation_message_id)
    WHERE conversation_message_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Grants: table-scoped, same policy as 0002/0003. Conversations are ordinary application
-- state, so app_rw gets full DML (users rename and delete their own threads). query_log is
-- deliberately absent from this block -- it keeps exactly the SELECT + INSERT it got in 0003.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON app.conversation         TO app_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON app.conversation_message TO app_rw;

COMMIT;
